var json_osm_3 = {
"type": "FeatureCollection",
"name": "osm_3",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "fid": "1", "osm_id": "109010581", "name": "Ferry Pasacaballo - Barú", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"amenity\"=>\"ferry_terminal\"" }, "geometry": { "type": "Point", "coordinates": [ -75.5219363, 10.2856569 ] } },
{ "type": "Feature", "properties": { "fid": "2", "osm_id": "282916376", "name": "Arjona", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": "town", "man_made": null, "other_tags": "\"name:ru\"=>\"Архона\",\"website\"=>\"https://arjona-bolivar.gov.co/\",\"wikidata\"=>\"Q671427\",\"wikipedia\"=>\"es:Arjona (Bolívar)\"" }, "geometry": { "type": "Point", "coordinates": [ -75.3427213, 10.2534632 ] } },
{ "type": "Feature", "properties": { "fid": "3", "osm_id": "355783731", "name": "Soplaviento", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": "town", "man_made": null, "other_tags": "\"wikidata\"=>\"Q1575590\",\"wikipedia\"=>\"en:Soplaviento\"" }, "geometry": { "type": "Point", "coordinates": [ -75.1369206, 10.3894704 ] } },
{ "type": "Feature", "properties": { "fid": "4", "osm_id": "458902741", "name": "Arroyohondo", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": "town", "man_made": null, "other_tags": null }, "geometry": { "type": "Point", "coordinates": [ -75.0190389, 10.2512203 ] } },
{ "type": "Feature", "properties": { "fid": "5", "osm_id": "703169690", "name": "Mahates", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": "town", "man_made": null, "other_tags": "\"comment\"=>\"convertido a OSM usando http://GaleNUx.com\",\"divipola\"=>\"13433\",\"wikidata\"=>\"Q1440795\",\"wikipedia\"=>\"en:Mahates\"" }, "geometry": { "type": "Point", "coordinates": [ -75.186894, 10.234262 ] } },
{ "type": "Feature", "properties": { "fid": "6", "osm_id": "703169693", "name": "San Estanislao (Arenal)", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": "town", "man_made": null, "other_tags": "\"comment\"=>\"convertido a OSM usando http://GaleNUx.com\",\"divipola\"=>\"13647\",\"local_name\"=>\"Arenal\",\"official_name\"=>\"San Estanislao de Kostka\",\"wikidata\"=>\"Q1525416\",\"wikipedia\"=>\"en:San Estanislao, Bolívar\"" }, "geometry": { "type": "Point", "coordinates": [ -75.1506023, 10.3992064 ] } },
{ "type": "Feature", "properties": { "fid": "7", "osm_id": "703210940", "name": "Bella Myrian", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": "Colombia; Bolívar ; Mahates", "place": "locality", "man_made": null, "other_tags": "\"comment\"=>\"convertido a OSM usando http://GaleNUx.com\",\"divipola\"=>\"13433\"" }, "geometry": { "type": "Point", "coordinates": [ -75.2395534, 10.2706773 ] } },
{ "type": "Feature", "properties": { "fid": "8", "osm_id": "703211538", "name": "Evitar", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": "Colombia; Bolívar ; Mahates", "place": "village", "man_made": null, "other_tags": "\"comment\"=>\"convertido a OSM usando http://GaleNUx.com\",\"divipola\"=>\"13433\"" }, "geometry": { "type": "Point", "coordinates": [ -75.1595084, 10.2721578 ] } },
{ "type": "Feature", "properties": { "fid": "9", "osm_id": "703211542", "name": "Gamero", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": "Colombia; Bolívar ; Mahates", "place": "village", "man_made": null, "other_tags": "\"comment\"=>\"convertido a OSM usando http://GaleNUx.com\",\"divipola\"=>\"13433\"" }, "geometry": { "type": "Point", "coordinates": [ -75.2121076, 10.206848 ] } },
{ "type": "Feature", "properties": { "fid": "10", "osm_id": "703211549", "name": "Mata De Caña", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": "Colombia; Bolívar ; Mahates", "place": "locality", "man_made": null, "other_tags": "\"comment\"=>\"convertido a OSM usando http://GaleNUx.com\",\"divipola\"=>\"13433\"" }, "geometry": { "type": "Point", "coordinates": [ -75.2155678, 10.2748252 ] } },
{ "type": "Feature", "properties": { "fid": "11", "osm_id": "703211566", "name": "La Peña", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": "Colombia; Bolívar ; Mahates", "place": "locality", "man_made": null, "other_tags": "\"comment\"=>\"convertido a OSM usando http://GaleNUx.com\",\"divipola\"=>\"13433\"" }, "geometry": { "type": "Point", "coordinates": [ -75.1860817, 10.1972777 ] } },
{ "type": "Feature", "properties": { "fid": "12", "osm_id": "703211571", "name": "Mahoma", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": "Colombia; Bolívar ; Mahates", "place": "locality", "man_made": null, "other_tags": "\"comment\"=>\"convertido a OSM usando http://GaleNUx.com\",\"divipola\"=>\"13433\"" }, "geometry": { "type": "Point", "coordinates": [ -75.2153874, 10.2618405 ] } },
{ "type": "Feature", "properties": { "fid": "13", "osm_id": "703211572", "name": "Angola", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": "Colombia; Bolívar ; Mahates", "place": "locality", "man_made": null, "other_tags": "\"comment\"=>\"convertido a OSM usando http://GaleNUx.com\",\"divipola\"=>\"13433\"" }, "geometry": { "type": "Point", "coordinates": [ -75.1423485, 10.2297394 ] } },
{ "type": "Feature", "properties": { "fid": "14", "osm_id": "915218479", "name": "Ferry Pasacaballo - Barú", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"amenity\"=>\"ferry_terminal\",\"ferry\"=>\"yes\",\"operator\"=>\"Public\",\"public_transport\"=>\"station\"" }, "geometry": { "type": "Point", "coordinates": [ -75.5218042, 10.2824092 ] } },
{ "type": "Feature", "properties": { "fid": "15", "osm_id": "1014548442", "name": null, "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"amenity\"=>\"ferry_terminal\"" }, "geometry": { "type": "Point", "coordinates": [ -75.1234665, 10.3994423 ] } },
{ "type": "Feature", "properties": { "fid": "16", "osm_id": "1296804207", "name": null, "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"amenity\"=>\"ferry_terminal\"" }, "geometry": { "type": "Point", "coordinates": [ -75.5205526, 10.2825012 ] } },
{ "type": "Feature", "properties": { "fid": "17", "osm_id": "1341104016", "name": null, "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"amenity\"=>\"ferry_terminal\"" }, "geometry": { "type": "Point", "coordinates": [ -75.1240447, 10.4004651 ] } },
{ "type": "Feature", "properties": { "fid": "18", "osm_id": "9437083889", "name": "Mahates", "barrier": null, "highway": null, "ref": "29037110", "address": null, "is_in": null, "place": null, "man_made": "monitoring_station", "other_tags": "\"addr:city\"=>\"Mahates\",\"addr:place\"=>\"Canal Del Dique\",\"addr:state\"=>\"Bolívar\",\"condition\"=>\"Suspendida\",\"description\"=>\"Limnimétrica\",\"display:analog\"=>\"yes\",\"monitoring:water_level\"=>\"yes\",\"operator\"=>\"Instituto De Hidrologia Meteorologia Y Estudios Ambientales\",\"recording:manually\"=>\"yes\"" }, "geometry": { "type": "Point", "coordinates": [ -75.2, 10.25 ] } },
{ "type": "Feature", "properties": { "fid": "19", "osm_id": "9437083890", "name": "Gamero", "barrier": null, "highway": null, "ref": "29030680;29030170", "address": null, "is_in": null, "place": null, "man_made": "monitoring_station", "other_tags": "\"addr:city\"=>\"Mahates\",\"addr:place\"=>\"Ariguani\",\"addr:state\"=>\"Bolívar\",\"condition\"=>\"Suspendida;Activa\",\"description\"=>\"Pluviométrica\",\"display:analog\"=>\"yes\",\"monitoring:rainfall\"=>\"yes\",\"operator\"=>\"Instituto De Hidrologia Meteorologia Y Estudios Ambientales\",\"recording:manually\"=>\"yes\"" }, "geometry": { "type": "Point", "coordinates": [ -75.2019444, 10.2002778 ] } },
{ "type": "Feature", "properties": { "fid": "20", "osm_id": "9437083895", "name": "Capote", "barrier": null, "highway": null, "ref": "29037702", "address": null, "is_in": null, "place": null, "man_made": "monitoring_station", "other_tags": "\"addr:city\"=>\"Mahates\",\"addr:place\"=>\"Canal Del Dique\",\"addr:state\"=>\"Bolívar\",\"condition\"=>\"Activa\",\"description\"=>\"Limnigráfica\",\"display:digital\"=>\"yes\",\"monitoring:water_level\"=>\"yes\",\"operator\"=>\"Instituto De Hidrologia Meteorologia Y Estudios Ambientales\",\"recording:automated\"=>\"yes\"" }, "geometry": { "type": "Point", "coordinates": [ -75.1653333, 10.2784444 ] } },
{ "type": "Feature", "properties": { "fid": "21", "osm_id": "9437083897", "name": "Mahates", "barrier": null, "highway": null, "ref": "14017701", "address": null, "is_in": null, "place": null, "man_made": "monitoring_station", "other_tags": "\"addr:city\"=>\"Mahates\",\"addr:place\"=>\"Canal Del Dique\",\"addr:state\"=>\"Bolívar\",\"condition\"=>\"Activa\",\"description\"=>\"Limnigráfica\",\"display:digital\"=>\"yes\",\"monitoring:water_level\"=>\"yes\",\"operator\"=>\"Instituto De Hidrologia Meteorologia Y Estudios Ambientales\",\"recording:automated\"=>\"yes\"" }, "geometry": { "type": "Point", "coordinates": [ -75.2038083, 10.2397861 ] } },
{ "type": "Feature", "properties": { "fid": "22", "osm_id": "9445855874", "name": "Matuya", "barrier": null, "highway": null, "ref": "29037007", "address": null, "is_in": null, "place": null, "man_made": "monitoring_station", "other_tags": "\"addr:city\"=>\"Mahates\",\"addr:place\"=>\"Ciénaga De Matuy\",\"addr:state\"=>\"Bolívar\",\"condition\"=>\"En Mantenimiento\",\"description\"=>\"Limnigráfica\",\"display:digital\"=>\"yes\",\"monitoring:water_level\"=>\"yes\",\"operator\"=>\"Instituto Colombiano De La Reforma Agraria\",\"recording:automated\"=>\"yes\"" }, "geometry": { "type": "Point", "coordinates": [ -75.2539278, 10.1839806 ] } }
]
}
